version: "3"

services:
  frontend:
    ports:
      - 8080:8080
    build:
      context: .
      target: install-deps
    volumes:
      - ./src:/app/src:z
      - ./public:/app/public:z
    command: sh -c "npm install --no-save @vue/cli-service && npm run serve"
