version: "3"

services:
  frontend:
    ports:
      - 8080:8080
    build:
      context: .
    volumes:
      - ./:/app:z
    command: sh -c "npm install --no-save @vue/cli-service && npm run serve"
